/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CommonResponseBodyOneArticleDto,
    CommonResponseBodyOneArticleDtoFromJSON,
    CommonResponseBodyOneArticleDtoToJSON,
} from '../models';

export interface GetRandomPinnedArticleOfApartmentUsingGETRequest {
    apartmentId: string;
}

/**
 * 
 */
export class Class4ArticleApi extends runtime.BaseAPI {

    /**
     * 사용자에게 보여질 pinned_article 랜덤 조회
     */
    async getRandomPinnedArticleOfApartmentUsingGETRaw(requestParameters: GetRandomPinnedArticleOfApartmentUsingGETRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyOneArticleDto>> {
        if (requestParameters.apartmentId === null || requestParameters.apartmentId === undefined) {
            throw new runtime.RequiredError('apartmentId','Required parameter requestParameters.apartmentId was null or undefined when calling getRandomPinnedArticleOfApartmentUsingGET.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // KarrotAccessToken authentication
        }

        const response = await this.request({
            path: `/api/v1/apartment/{apartmentId}/articles/pinned`.replace(`{${"apartmentId"}}`, encodeURIComponent(String(requestParameters.apartmentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyOneArticleDtoFromJSON(jsonValue));
    }

    /**
     * 사용자에게 보여질 pinned_article 랜덤 조회
     */
    async getRandomPinnedArticleOfApartmentUsingGET(requestParameters: GetRandomPinnedArticleOfApartmentUsingGETRequest, initOverrides?: RequestInit): Promise<CommonResponseBodyOneArticleDto> {
        const response = await this.getRandomPinnedArticleOfApartmentUsingGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
