/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CommonResponseBodyGetCommentsOfQuestionDto,
    CommonResponseBodyGetCommentsOfQuestionDtoFromJSON,
    CommonResponseBodyGetCommentsOfQuestionDtoToJSON,
    CommonResponseBodyVoid,
    CommonResponseBodyVoidFromJSON,
    CommonResponseBodyVoidToJSON,
    WriteNewCommentDto,
    WriteNewCommentDtoFromJSON,
    WriteNewCommentDtoToJSON,
} from '../models';

export interface GetCommentsOfQuestionUsingGETRequest {
    questionId: string;
}

export interface WriteNewCommentUsingPOSTRequest {
    questionId: string;
    commentContent: WriteNewCommentDto;
}

/**
 * 
 */
export class Class5Api extends runtime.BaseAPI {

    /**
     * 질문에 달린 게시글 보기
     */
    async getCommentsOfQuestionUsingGETRaw(requestParameters: GetCommentsOfQuestionUsingGETRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyGetCommentsOfQuestionDto>> {
        if (requestParameters.questionId === null || requestParameters.questionId === undefined) {
            throw new runtime.RequiredError('questionId','Required parameter requestParameters.questionId was null or undefined when calling getCommentsOfQuestionUsingGET.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // KarrotAccessToken authentication
        }

        const response = await this.request({
            path: `/api/v1/question/{questionId}/comments`.replace(`{${"questionId"}}`, encodeURIComponent(String(requestParameters.questionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyGetCommentsOfQuestionDtoFromJSON(jsonValue));
    }

    /**
     * 질문에 달린 게시글 보기
     */
    async getCommentsOfQuestionUsingGET(requestParameters: GetCommentsOfQuestionUsingGETRequest, initOverrides?: RequestInit): Promise<CommonResponseBodyGetCommentsOfQuestionDto> {
        const response = await this.getCommentsOfQuestionUsingGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 새로운 댓글 작성
     */
    async writeNewCommentUsingPOSTRaw(requestParameters: WriteNewCommentUsingPOSTRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyVoid>> {
        if (requestParameters.questionId === null || requestParameters.questionId === undefined) {
            throw new runtime.RequiredError('questionId','Required parameter requestParameters.questionId was null or undefined when calling writeNewCommentUsingPOST.');
        }

        if (requestParameters.commentContent === null || requestParameters.commentContent === undefined) {
            throw new runtime.RequiredError('commentContent','Required parameter requestParameters.commentContent was null or undefined when calling writeNewCommentUsingPOST.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // KarrotAccessToken authentication
        }

        const response = await this.request({
            path: `/api/v1/question/{questionId}/comment`.replace(`{${"questionId"}}`, encodeURIComponent(String(requestParameters.questionId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WriteNewCommentDtoToJSON(requestParameters.commentContent),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyVoidFromJSON(jsonValue));
    }

    /**
     * 새로운 댓글 작성
     */
    async writeNewCommentUsingPOST(requestParameters: WriteNewCommentUsingPOSTRequest, initOverrides?: RequestInit): Promise<CommonResponseBodyVoid> {
        const response = await this.writeNewCommentUsingPOSTRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
