/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CommonResponseBodyGetApartmentInRegionDto,
    CommonResponseBodyGetApartmentInRegionDtoFromJSON,
    CommonResponseBodyGetApartmentInRegionDtoToJSON,
} from '../models';

export interface GetApartmentInRegionUsingGETRequest {
    regionId: string;
}

/**
 * 
 */
export class Class2Api extends runtime.BaseAPI {

    /**
     * 해당 리전에 포함된 아파트들 가져오기
     */
    async getApartmentInRegionUsingGETRaw(requestParameters: GetApartmentInRegionUsingGETRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyGetApartmentInRegionDto>> {
        if (requestParameters.regionId === null || requestParameters.regionId === undefined) {
            throw new runtime.RequiredError('regionId','Required parameter requestParameters.regionId was null or undefined when calling getApartmentInRegionUsingGET.');
        }

        const queryParameters: any = {};

        if (requestParameters.regionId !== undefined) {
            queryParameters['regionId'] = requestParameters.regionId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/apartments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyGetApartmentInRegionDtoFromJSON(jsonValue));
    }

    /**
     * 해당 리전에 포함된 아파트들 가져오기
     */
    async getApartmentInRegionUsingGET(requestParameters: GetApartmentInRegionUsingGETRequest, initOverrides?: RequestInit): Promise<CommonResponseBodyGetApartmentInRegionDto> {
        const response = await this.getApartmentInRegionUsingGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
