/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CommonResponseBodyGetAvailableApartmentsDto,
    CommonResponseBodyGetAvailableApartmentsDtoFromJSON,
    CommonResponseBodyGetAvailableApartmentsDtoToJSON,
} from '../models';

/**
 * 
 */
export class Class2Api extends runtime.BaseAPI {

    /**
     * 해당 리전에 포함된 아파트들 가져오기
     */
    async getAvailableApartmentsUsingGETRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyGetAvailableApartmentsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/apartments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyGetAvailableApartmentsDtoFromJSON(jsonValue));
    }

    /**
     * 해당 리전에 포함된 아파트들 가져오기
     */
    async getAvailableApartmentsUsingGET(initOverrides?: RequestInit): Promise<CommonResponseBodyGetAvailableApartmentsDto> {
        const response = await this.getAvailableApartmentsUsingGETRaw(initOverrides);
        return await response.value();
    }

}
