/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CommonResponseBodyVoid,
    CommonResponseBodyVoidFromJSON,
    CommonResponseBodyVoidToJSON,
    SurveyDto,
    SurveyDtoFromJSON,
    SurveyDtoToJSON,
} from '../models';

export interface SubmitSurveyUsingPOSTRequest {
    form: SurveyDto;
}

/**
 * 
 */
export class ControllerApi extends runtime.BaseAPI {

    /**
     * [임시] 설문조사 제출
     */
    async submitSurveyUsingPOSTRaw(requestParameters: SubmitSurveyUsingPOSTRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CommonResponseBodyVoid>> {
        if (requestParameters.form === null || requestParameters.form === undefined) {
            throw new runtime.RequiredError('form','Required parameter requestParameters.form was null or undefined when calling submitSurveyUsingPOST.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // KarrotAccessToken authentication
        }

        const response = await this.request({
            path: `/api/v1/survey`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SurveyDtoToJSON(requestParameters.form),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseBodyVoidFromJSON(jsonValue));
    }

    /**
     * [임시] 설문조사 제출
     */
    async submitSurveyUsingPOST(requestParameters: SubmitSurveyUsingPOSTRequest, initOverrides?: RequestInit): Promise<CommonResponseBodyVoid> {
        const response = await this.submitSurveyUsingPOSTRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
