/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegionDto,
    RegionDtoFromJSON,
    RegionDtoFromJSONTyped,
    RegionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApartmentDto
 */
export interface ApartmentDto {
    /**
     * 
     * @type {boolean}
     * @memberof ApartmentDto
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    bannerImage: string;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    brandName: string;
    /**
     * 
     * @type {Date}
     * @memberof ApartmentDto
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    name: string;
    /**
     * 
     * @type {RegionDto}
     * @memberof ApartmentDto
     */
    regionDepth1: RegionDto;
    /**
     * 
     * @type {RegionDto}
     * @memberof ApartmentDto
     */
    regionDepth2: RegionDto;
    /**
     * 
     * @type {RegionDto}
     * @memberof ApartmentDto
     */
    regionDepth3: RegionDto;
    /**
     * 
     * @type {RegionDto}
     * @memberof ApartmentDto
     */
    regionDepth4?: RegionDto;
    /**
     * 
     * @type {Date}
     * @memberof ApartmentDto
     */
    updatedAt: Date;
}

export function ApartmentDtoFromJSON(json: any): ApartmentDto {
    return ApartmentDtoFromJSONTyped(json, false);
}

export function ApartmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'bannerImage': json['bannerImage'],
        'brandName': json['brandName'],
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'name': json['name'],
        'regionDepth1': RegionDtoFromJSON(json['regionDepth1']),
        'regionDepth2': RegionDtoFromJSON(json['regionDepth2']),
        'regionDepth3': RegionDtoFromJSON(json['regionDepth3']),
        'regionDepth4': !exists(json, 'regionDepth4') ? undefined : RegionDtoFromJSON(json['regionDepth4']),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ApartmentDtoToJSON(value?: ApartmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'bannerImage': value.bannerImage,
        'brandName': value.brandName,
        'createdAt': (value.createdAt.toISOString()),
        'id': value.id,
        'name': value.name,
        'regionDepth1': RegionDtoToJSON(value.regionDepth1),
        'regionDepth2': RegionDtoToJSON(value.regionDepth2),
        'regionDepth3': RegionDtoToJSON(value.regionDepth3),
        'regionDepth4': RegionDtoToJSON(value.regionDepth4),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

