/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  GetApartmentInRegionDto,
  GetApartmentInRegionDtoFromJSON,
  GetApartmentInRegionDtoFromJSONTyped,
  GetApartmentInRegionDtoToJSON,
} from "./";

/**
 *
 * @export
 * @interface CommonResponseBodyGetApartmentInRegionDto
 */
export interface CommonResponseBodyGetApartmentInRegionDto {
  /**
   *
   * @type {GetApartmentInRegionDto}
   * @memberof CommonResponseBodyGetApartmentInRegionDto
   */
  data?: GetApartmentInRegionDto;
  /**
   *
   * @type {string}
   * @memberof CommonResponseBodyGetApartmentInRegionDto
   */
  devMessage: string;
  /**
   *
   * @type {string}
   * @memberof CommonResponseBodyGetApartmentInRegionDto
   */
  displayMessage: string;
  /**
   *
   * @type {string}
   * @memberof CommonResponseBodyGetApartmentInRegionDto
   */
  status: CommonResponseBodyGetApartmentInRegionDtoStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CommonResponseBodyGetApartmentInRegionDtoStatusEnum {
  DataNotFoundFromDb = "DATA_NOT_FOUND_FROM_DB",
  InvalidInput = "INVALID_INPUT",
  KarrotInvalidAccessToken = "KARROT_INVALID_ACCESS_TOKEN",
  KarrotUnauthorizedCode = "KARROT_UNAUTHORIZED_CODE",
  NotCheckedInUser = "NOT_CHECKED_IN_USER",
  NotServicedRegion = "NOT_SERVICED_REGION",
  RegisteredUserNotFound = "REGISTERED_USER_NOT_FOUND",
  ResourceDuplicate = "RESOURCE_DUPLICATE",
  Success = "SUCCESS",
}

export function CommonResponseBodyGetApartmentInRegionDtoFromJSON(
  json: any
): CommonResponseBodyGetApartmentInRegionDto {
  return CommonResponseBodyGetApartmentInRegionDtoFromJSONTyped(json, false);
}

export function CommonResponseBodyGetApartmentInRegionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonResponseBodyGetApartmentInRegionDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : GetApartmentInRegionDtoFromJSON(json["data"]),
    devMessage: json["devMessage"],
    displayMessage: json["displayMessage"],
    status: json["status"],
  };
}

export function CommonResponseBodyGetApartmentInRegionDtoToJSON(
  value?: CommonResponseBodyGetApartmentInRegionDto | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: GetApartmentInRegionDtoToJSON(value.data),
    devMessage: value.devMessage,
    displayMessage: value.displayMessage,
    status: value.status,
  };
}
