/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OneQuestionDto,
    OneQuestionDtoFromJSON,
    OneQuestionDtoFromJSONTyped,
    OneQuestionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResponseBodyOneQuestionDto
 */
export interface CommonResponseBodyOneQuestionDto {
    /**
     * 
     * @type {OneQuestionDto}
     * @memberof CommonResponseBodyOneQuestionDto
     */
    data?: OneQuestionDto;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneQuestionDto
     */
    devMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneQuestionDto
     */
    displayMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneQuestionDto
     */
    status: CommonResponseBodyOneQuestionDtoStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum CommonResponseBodyOneQuestionDtoStatusEnum {
    BannedUser = 'BANNED_USER',
    DataNotFoundFromDb = 'DATA_NOT_FOUND_FROM_DB',
    InvalidInput = 'INVALID_INPUT',
    KarrotInvalidAccessToken = 'KARROT_INVALID_ACCESS_TOKEN',
    KarrotUnauthorizedCode = 'KARROT_UNAUTHORIZED_CODE',
    NotCheckedInUser = 'NOT_CHECKED_IN_USER',
    NotServicedRegion = 'NOT_SERVICED_REGION',
    RegisteredUserNotFound = 'REGISTERED_USER_NOT_FOUND',
    ResourceDuplicate = 'RESOURCE_DUPLICATE',
    Success = 'SUCCESS'
}

export function CommonResponseBodyOneQuestionDtoFromJSON(json: any): CommonResponseBodyOneQuestionDto {
    return CommonResponseBodyOneQuestionDtoFromJSONTyped(json, false);
}

export function CommonResponseBodyOneQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseBodyOneQuestionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : OneQuestionDtoFromJSON(json['data']),
        'devMessage': json['devMessage'],
        'displayMessage': json['displayMessage'],
        'status': json['status'],
    };
}

export function CommonResponseBodyOneQuestionDtoToJSON(value?: CommonResponseBodyOneQuestionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': OneQuestionDtoToJSON(value.data),
        'devMessage': value.devMessage,
        'displayMessage': value.displayMessage,
        'status': value.status,
    };
}

