/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonResponseBodyVoid
 */
export interface CommonResponseBodyVoid {
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyVoid
     */
    devMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyVoid
     */
    displayMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyVoid
     */
    status: CommonResponseBodyVoidStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum CommonResponseBodyVoidStatusEnum {
    BannedUser = 'BANNED_USER',
    DataNotFoundFromDb = 'DATA_NOT_FOUND_FROM_DB',
    InvalidInput = 'INVALID_INPUT',
    KarrotInvalidAccessToken = 'KARROT_INVALID_ACCESS_TOKEN',
    KarrotUnauthorizedCode = 'KARROT_UNAUTHORIZED_CODE',
    NotCheckedInUser = 'NOT_CHECKED_IN_USER',
    NotServicedRegion = 'NOT_SERVICED_REGION',
    RegisteredUserNotFound = 'REGISTERED_USER_NOT_FOUND',
    ResourceDuplicate = 'RESOURCE_DUPLICATE',
    Success = 'SUCCESS'
}

export function CommonResponseBodyVoidFromJSON(json: any): CommonResponseBodyVoid {
    return CommonResponseBodyVoidFromJSONTyped(json, false);
}

export function CommonResponseBodyVoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseBodyVoid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'devMessage': json['devMessage'],
        'displayMessage': json['displayMessage'],
        'status': json['status'],
    };
}

export function CommonResponseBodyVoidToJSON(value?: CommonResponseBodyVoid | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'devMessage': value.devMessage,
        'displayMessage': value.displayMessage,
        'status': value.status,
    };
}

