/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OneArticleDto,
    OneArticleDtoFromJSON,
    OneArticleDtoFromJSONTyped,
    OneArticleDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResponseBodyOneArticleDto
 */
export interface CommonResponseBodyOneArticleDto {
    /**
     * 
     * @type {OneArticleDto}
     * @memberof CommonResponseBodyOneArticleDto
     */
    data?: OneArticleDto;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneArticleDto
     */
    devMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneArticleDto
     */
    displayMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseBodyOneArticleDto
     */
    status: CommonResponseBodyOneArticleDtoStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum CommonResponseBodyOneArticleDtoStatusEnum {
    BannedUser = 'BANNED_USER',
    DataNotFoundFromDb = 'DATA_NOT_FOUND_FROM_DB',
    InvalidInput = 'INVALID_INPUT',
    KarrotInvalidAccessToken = 'KARROT_INVALID_ACCESS_TOKEN',
    KarrotUnauthorizedCode = 'KARROT_UNAUTHORIZED_CODE',
    NotCheckedInUser = 'NOT_CHECKED_IN_USER',
    NotServicedRegion = 'NOT_SERVICED_REGION',
    NoPermission = 'NO_PERMISSION',
    RegisteredUserNotFound = 'REGISTERED_USER_NOT_FOUND',
    ResourceDuplicate = 'RESOURCE_DUPLICATE',
    Success = 'SUCCESS'
}

export function CommonResponseBodyOneArticleDtoFromJSON(json: any): CommonResponseBodyOneArticleDto {
    return CommonResponseBodyOneArticleDtoFromJSONTyped(json, false);
}

export function CommonResponseBodyOneArticleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseBodyOneArticleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : OneArticleDtoFromJSON(json['data']),
        'devMessage': json['devMessage'],
        'displayMessage': json['displayMessage'],
        'status': json['status'],
    };
}

export function CommonResponseBodyOneArticleDtoToJSON(value?: CommonResponseBodyOneArticleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': OneArticleDtoToJSON(value.data),
        'devMessage': value.devMessage,
        'displayMessage': value.displayMessage,
        'status': value.status,
    };
}

