/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommentDto,
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
    VoteDto,
    VoteDtoFromJSON,
    VoteDtoFromJSONTyped,
    VoteDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeedItemDto
 */
export interface FeedItemDto {
    /**
     * 
     * @type {CommentDto}
     * @memberof FeedItemDto
     */
    lastComment?: CommentDto;
    /**
     * 
     * @type {VoteDto}
     * @memberof FeedItemDto
     */
    vote: VoteDto;
}

export function FeedItemDtoFromJSON(json: any): FeedItemDto {
    return FeedItemDtoFromJSONTyped(json, false);
}

export function FeedItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastComment': !exists(json, 'lastComment') ? undefined : CommentDtoFromJSON(json['lastComment']),
        'vote': VoteDtoFromJSON(json['vote']),
    };
}

export function FeedItemDtoToJSON(value?: FeedItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastComment': CommentDtoToJSON(value.lastComment),
        'vote': VoteDtoToJSON(value.vote),
    };
}

