/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeedItemDto,
    FeedItemDtoFromJSON,
    FeedItemDtoFromJSONTyped,
    FeedItemDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeedDto
 */
export interface FeedDto {
    /**
     * 
     * @type {Array<FeedItemDto>}
     * @memberof FeedDto
     */
    items: Array<FeedItemDto>;
}

export function FeedDtoFromJSON(json: any): FeedDto {
    return FeedDtoFromJSONTyped(json, false);
}

export function FeedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FeedItemDtoFromJSON)),
    };
}

export function FeedDtoToJSON(value?: FeedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(FeedItemDtoToJSON)),
    };
}

