/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApartmentDto,
    ApartmentDtoFromJSON,
    ApartmentDtoFromJSONTyped,
    ApartmentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetApartmentInRegionDto
 */
export interface GetApartmentInRegionDto {
    /**
     * 
     * @type {Array<ApartmentDto>}
     * @memberof GetApartmentInRegionDto
     */
    apartments: Array<ApartmentDto>;
}

export function GetApartmentInRegionDtoFromJSON(json: any): GetApartmentInRegionDto {
    return GetApartmentInRegionDtoFromJSONTyped(json, false);
}

export function GetApartmentInRegionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApartmentInRegionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apartments': ((json['apartments'] as Array<any>).map(ApartmentDtoFromJSON)),
    };
}

export function GetApartmentInRegionDtoToJSON(value?: GetApartmentInRegionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apartments': ((value.apartments as Array<any>).map(ApartmentDtoToJSON)),
    };
}

