/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommentDto,
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetCommentsOfQuestionDto
 */
export interface GetCommentsOfQuestionDto {
    /**
     * 
     * @type {Array<CommentDto>}
     * @memberof GetCommentsOfQuestionDto
     */
    comments?: Array<CommentDto>;
}

export function GetCommentsOfQuestionDtoFromJSON(json: any): GetCommentsOfQuestionDto {
    return GetCommentsOfQuestionDtoFromJSONTyped(json, false);
}

export function GetCommentsOfQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCommentsOfQuestionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comments': !exists(json, 'comments') ? undefined : ((json['comments'] as Array<any>).map(CommentDtoFromJSON)),
    };
}

export function GetCommentsOfQuestionDtoToJSON(value?: GetCommentsOfQuestionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comments': value.comments === undefined ? undefined : ((value.comments as Array<any>).map(CommentDtoToJSON)),
    };
}

