/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetOneUserDto
 */
export interface GetOneUserDto {
    /**
     * 
     * @type {UserDto}
     * @memberof GetOneUserDto
     */
    user?: UserDto;
}

export function GetOneUserDtoFromJSON(json: any): GetOneUserDto {
    return GetOneUserDtoFromJSONTyped(json, false);
}

export function GetOneUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOneUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserDtoFromJSON(json['user']),
    };
}

export function GetOneUserDtoToJSON(value?: GetOneUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDtoToJSON(value.user),
    };
}

