/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    QuestionDto,
    QuestionDtoFromJSON,
    QuestionDtoFromJSONTyped,
    QuestionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetQuestionsDto
 */
export interface GetQuestionsDto {
    /**
     * 
     * @type {Array<QuestionDto>}
     * @memberof GetQuestionsDto
     */
    questions: Array<QuestionDto>;
}

export function GetQuestionsDtoFromJSON(json: any): GetQuestionsDto {
    return GetQuestionsDtoFromJSONTyped(json, false);
}

export function GetQuestionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetQuestionsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questions': ((json['questions'] as Array<any>).map(QuestionDtoFromJSON)),
    };
}

export function GetQuestionsDtoToJSON(value?: GetQuestionsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questions': ((value.questions as Array<any>).map(QuestionDtoToJSON)),
    };
}

