/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    QuestionDto,
    QuestionDtoFromJSON,
    QuestionDtoFromJSONTyped,
    QuestionDtoToJSON,
    VoteDto,
    VoteDtoFromJSON,
    VoteDtoFromJSONTyped,
    VoteDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OneArticleDto
 */
export interface OneArticleDto {
    /**
     * 
     * @type {QuestionDto}
     * @memberof OneArticleDto
     */
    question?: QuestionDto;
    /**
     * 
     * @type {VoteDto}
     * @memberof OneArticleDto
     */
    vote?: VoteDto;
}

export function OneArticleDtoFromJSON(json: any): OneArticleDto {
    return OneArticleDtoFromJSONTyped(json, false);
}

export function OneArticleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneArticleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'question': !exists(json, 'question') ? undefined : QuestionDtoFromJSON(json['question']),
        'vote': !exists(json, 'vote') ? undefined : VoteDtoFromJSON(json['vote']),
    };
}

export function OneArticleDtoToJSON(value?: OneArticleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'question': QuestionDtoToJSON(value.question),
        'vote': VoteDtoToJSON(value.vote),
    };
}

