/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApartmentDto,
    ApartmentDtoFromJSON,
    ApartmentDtoFromJSONTyped,
    ApartmentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OneApartmentDto
 */
export interface OneApartmentDto {
    /**
     * 
     * @type {ApartmentDto}
     * @memberof OneApartmentDto
     */
    apartment?: ApartmentDto;
}

export function OneApartmentDtoFromJSON(json: any): OneApartmentDto {
    return OneApartmentDtoFromJSONTyped(json, false);
}

export function OneApartmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneApartmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apartment': !exists(json, 'apartment') ? undefined : ApartmentDtoFromJSON(json['apartment']),
    };
}

export function OneApartmentDtoToJSON(value?: OneApartmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apartment': ApartmentDtoToJSON(value.apartment),
    };
}

