/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommentDto,
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OneCommentDto
 */
export interface OneCommentDto {
    /**
     * 
     * @type {CommentDto}
     * @memberof OneCommentDto
     */
    comment?: CommentDto;
}

export function OneCommentDtoFromJSON(json: any): OneCommentDto {
    return OneCommentDtoFromJSONTyped(json, false);
}

export function OneCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneCommentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : CommentDtoFromJSON(json['comment']),
    };
}

export function OneCommentDtoToJSON(value?: OneCommentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': CommentDtoToJSON(value.comment),
    };
}

