/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OneUserDto
 */
export interface OneUserDto {
    /**
     * 
     * @type {UserDto}
     * @memberof OneUserDto
     */
    user?: UserDto;
}

export function OneUserDtoFromJSON(json: any): OneUserDto {
    return OneUserDtoFromJSONTyped(json, false);
}

export function OneUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserDtoFromJSON(json['user']),
    };
}

export function OneUserDtoToJSON(value?: OneUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDtoToJSON(value.user),
    };
}

