/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    VoteDto,
    VoteDtoFromJSON,
    VoteDtoFromJSONTyped,
    VoteDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OneVoteDto
 */
export interface OneVoteDto {
    /**
     * 
     * @type {VoteDto}
     * @memberof OneVoteDto
     */
    vote: VoteDto;
}

export function OneVoteDtoFromJSON(json: any): OneVoteDto {
    return OneVoteDtoFromJSONTyped(json, false);
}

export function OneVoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneVoteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vote': VoteDtoFromJSON(json['vote']),
    };
}

export function OneVoteDtoToJSON(value?: OneVoteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vote': VoteDtoToJSON(value.vote),
    };
}

