/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionContentDto
 */
export interface QuestionContentDto {
    /**
     * 
     * @type {string}
     * @memberof QuestionContentDto
     */
    mainText: string;
}

export function QuestionContentDtoFromJSON(json: any): QuestionContentDto {
    return QuestionContentDtoFromJSONTyped(json, false);
}

export function QuestionContentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionContentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mainText': json['mainText'],
    };
}

export function QuestionContentDtoToJSON(value?: QuestionContentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mainText': value.mainText,
    };
}

