/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KarrotProfile,
    KarrotProfileFromJSON,
    KarrotProfileFromJSONTyped,
    KarrotProfileToJSON,
} from './';

/**
 * 
 * @export
 * @interface QuestionDto
 */
export interface QuestionDto {
    /**
     * 
     * @type {boolean}
     * @memberof QuestionDto
     */
    byAdmin: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuestionDto
     */
    countOfComments: number;
    /**
     * 
     * @type {Date}
     * @memberof QuestionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof QuestionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionDto
     */
    mainText: string;
    /**
     * 
     * @type {Date}
     * @memberof QuestionDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {KarrotProfile}
     * @memberof QuestionDto
     */
    writer: KarrotProfile;
}

export function QuestionDtoFromJSON(json: any): QuestionDto {
    return QuestionDtoFromJSONTyped(json, false);
}

export function QuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'byAdmin': json['byAdmin'],
        'countOfComments': json['countOfComments'],
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'mainText': json['mainText'],
        'updatedAt': (new Date(json['updatedAt'])),
        'writer': KarrotProfileFromJSON(json['writer']),
    };
}

export function QuestionDtoToJSON(value?: QuestionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'byAdmin': value.byAdmin,
        'countOfComments': value.countOfComments,
        'createdAt': (value.createdAt.toISOString()),
        'id': value.id,
        'mainText': value.mainText,
        'updatedAt': (value.updatedAt.toISOString()),
        'writer': KarrotProfileToJSON(value.writer),
    };
}

