/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegionDto
 */
export interface RegionDto {
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    name: string;
}

export function RegionDtoFromJSON(json: any): RegionDto {
    return RegionDtoFromJSONTyped(json, false);
}

export function RegionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function RegionDtoToJSON(value?: RegionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

