/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SurveyDto
 */
export interface SurveyDto {
    /**
     * 
     * @type {string}
     * @memberof SurveyDto
     */
    contentJson?: string;
}

export function SurveyDtoFromJSON(json: any): SurveyDto {
    return SurveyDtoFromJSONTyped(json, false);
}

export function SurveyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurveyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentJson': !exists(json, 'contentJson') ? undefined : json['contentJson'],
    };
}

export function SurveyDtoToJSON(value?: SurveyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentJson': value.contentJson,
    };
}

