/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KarrotProfile,
    KarrotProfileFromJSON,
    KarrotProfileFromJSONTyped,
    KarrotProfileToJSON,
    VoteItemDto,
    VoteItemDtoFromJSON,
    VoteItemDtoFromJSONTyped,
    VoteItemDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface VoteDto
 */
export interface VoteDto {
    /**
     * 
     * @type {boolean}
     * @memberof VoteDto
     */
    byAdmin: boolean;
    /**
     * 
     * @type {number}
     * @memberof VoteDto
     */
    countOfComments: number;
    /**
     * 
     * @type {Date}
     * @memberof VoteDto
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof VoteDto
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoteDto
     */
    isInProgress: boolean;
    /**
     * 
     * @type {Array<VoteItemDto>}
     * @memberof VoteDto
     */
    items: Array<VoteItemDto>;
    /**
     * 
     * @type {string}
     * @memberof VoteDto
     */
    mainText: string;
    /**
     * 
     * @type {Date}
     * @memberof VoteDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {KarrotProfile}
     * @memberof VoteDto
     */
    writer: KarrotProfile;
}

export function VoteDtoFromJSON(json: any): VoteDto {
    return VoteDtoFromJSONTyped(json, false);
}

export function VoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'byAdmin': json['byAdmin'],
        'countOfComments': json['countOfComments'],
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'isInProgress': json['isInProgress'],
        'items': ((json['items'] as Array<any>).map(VoteItemDtoFromJSON)),
        'mainText': json['mainText'],
        'updatedAt': (new Date(json['updatedAt'])),
        'writer': KarrotProfileFromJSON(json['writer']),
    };
}

export function VoteDtoToJSON(value?: VoteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'byAdmin': value.byAdmin,
        'countOfComments': value.countOfComments,
        'createdAt': (value.createdAt.toISOString()),
        'id': value.id,
        'isInProgress': value.isInProgress,
        'items': ((value.items as Array<any>).map(VoteItemDtoToJSON)),
        'mainText': value.mainText,
        'updatedAt': (value.updatedAt.toISOString()),
        'writer': KarrotProfileToJSON(value.writer),
    };
}

