/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    VoteDto,
    VoteDtoFromJSON,
    VoteDtoFromJSONTyped,
    VoteDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface VoteListDto
 */
export interface VoteListDto {
    /**
     * 
     * @type {Array<VoteDto>}
     * @memberof VoteListDto
     */
    votes?: Array<VoteDto>;
}

export function VoteListDtoFromJSON(json: any): VoteListDto {
    return VoteListDtoFromJSONTyped(json, false);
}

export function VoteListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteListDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'votes': !exists(json, 'votes') ? undefined : ((json['votes'] as Array<any>).map(VoteDtoFromJSON)),
    };
}

export function VoteListDtoToJSON(value?: VoteListDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'votes': value.votes === undefined ? undefined : ((value.votes as Array<any>).map(VoteDtoToJSON)),
    };
}

