/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteNewQuestionDto
 */
export interface WriteNewQuestionDto {
    /**
     * 
     * @type {string}
     * @memberof WriteNewQuestionDto
     */
    mainText: string;
    /**
     * 
     * @type {string}
     * @memberof WriteNewQuestionDto
     */
    regionId: string;
}

export function WriteNewQuestionDtoFromJSON(json: any): WriteNewQuestionDto {
    return WriteNewQuestionDtoFromJSONTyped(json, false);
}

export function WriteNewQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteNewQuestionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mainText': json['mainText'],
        'regionId': json['regionId'],
    };
}

export function WriteNewQuestionDtoToJSON(value?: WriteNewQuestionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mainText': value.mainText,
        'regionId': value.regionId,
    };
}

