/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteNewCommentDto
 */
export interface WriteNewCommentDto {
    /**
     * 
     * @type {string}
     * @memberof WriteNewCommentDto
     */
    mainText: string;
    /**
     * 
     * @type {string}
     * @memberof WriteNewCommentDto
     */
    regionId: string;
}

export function WriteNewCommentDtoFromJSON(json: any): WriteNewCommentDto {
    return WriteNewCommentDtoFromJSONTyped(json, false);
}

export function WriteNewCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteNewCommentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mainText': json['mainText'],
        'regionId': json['regionId'],
    };
}

export function WriteNewCommentDtoToJSON(value?: WriteNewCommentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mainText': value.mainText,
        'regionId': value.regionId,
    };
}

