/* tslint:disable */
/* eslint-disable */
/**
 * 우리아파트 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KarrotAccessTokenDto
 */
export interface KarrotAccessTokenDto {
    /**
     * 
     * @type {string}
     * @memberof KarrotAccessTokenDto
     */
    accessToken?: string;
    /**
     * 
     * @type {number}
     * @memberof KarrotAccessTokenDto
     */
    expiredIn?: number;
    /**
     * 
     * @type {string}
     * @memberof KarrotAccessTokenDto
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof KarrotAccessTokenDto
     */
    tokenType?: string;
}

export function KarrotAccessTokenDtoFromJSON(json: any): KarrotAccessTokenDto {
    return KarrotAccessTokenDtoFromJSONTyped(json, false);
}

export function KarrotAccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KarrotAccessTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'expiredIn': !exists(json, 'expiredIn') ? undefined : json['expiredIn'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'tokenType': !exists(json, 'tokenType') ? undefined : json['tokenType'],
    };
}

export function KarrotAccessTokenDtoToJSON(value?: KarrotAccessTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'expiredIn': value.expiredIn,
        'scope': value.scope,
        'tokenType': value.tokenType,
    };
}

