# This is a basic workflow to help you get started with Actions

name: CI_ALPHA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [alpha]
  # pull_request:
  #   branches: [alpha]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.1

      # Build React
      - name: Build React
        run: |
          echo "Env Checking..."
          echo "REACT_APP_ID=${REACT_APP_ID}"
          echo "REACT_APP_PRESET_URL=${REACT_APP_PRESET_URL}"
          echo "NODE_VERSION is"
          node --version
          echo "NPM_VERSION is"
          npm --version
          npm install 

          echo "Build Starting..."
          npm run build
        env:
          REACT_APP_ID: ${{ secrets.ALPHA_REACT_APP_ID }}
          REACT_APP_PRESET_URL: ${{ secrets.ALPHA_REACT_APP_ID }}

      # Setup AWS
      - name: Setup AWS with credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://ourapt-client-alpha

      # Invalidate Cloudfront
      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.ALPHA_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
